### ISSUE TITLE
Hello, my test dataset uses velodyne VLS 128. Can you use your preserved model? Anything to watch out for?

### ISSUE THREAD

**Issue by ferrari700** [matlab-deep-learning/pretrained-salsanext#1]

**Comment by vancha-MW** [comment]
There are two ways to solve this issue:

1. You can use the lidarParameters and pcorganize function to convert the test dataset into required format and use the preserved model.
2. You can train the network using salsaNextTransferLearning.m on your own dataset.

As the pretrained model shared in the repository is on Pandar sensor and the sensor used for your dataset is VLS128 it is recommended to train the network on your dataset (step 2).
